// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth": {
            "get": {
                "description": "Authenticates a user Basic Auth against Active Directory and generates a JWT token",
                "tags": [
                    "auth"
                ],
                "summary": "AD Authentication",
                "responses": {
                    "200": {
                        "description": "Authenticated successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Authentication failed",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/fimrware": {
            "post": {
                "description": "This endpoint updates the firmware of a BMC device.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "update"
                ],
                "summary": "Firmware Update for BMC",
                "parameters": [
                    {
                        "description": "Firmware Update request parameters",
                        "name": "firmware_request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.FirmwareUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success response",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/fimrwareinfo": {
            "post": {
                "description": "This endpoint fetches the firmware info of a BMC device.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "info"
                ],
                "summary": "Firmware Info for BMC",
                "parameters": [
                    {
                        "description": "Firmware info request parameters",
                        "name": "firmware_info",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.FirmwareInfoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success response",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/power": {
            "post": {
                "description": "This endpoint allows the user to power on/off/reset a BMC device.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "power"
                ],
                "summary": "Manage power for BMC",
                "parameters": [
                    {
                        "description": "Power request parameters",
                        "name": "power_request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.PowerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success response",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/systeminfo": {
            "post": {
                "description": "This endpoint fetches the system info of a BMC device.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "info"
                ],
                "summary": "System Info for BMC",
                "parameters": [
                    {
                        "description": "System Info request parameters",
                        "name": "system_info",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.SystemInfoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success response",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.BMCType": {
            "type": "string",
            "enum": [
                "dell",
                "hpe",
                "lenovoxcc",
                "lenovoimm",
                "nutanix"
            ],
            "x-enum-varnames": [
                "Dell",
                "HPE",
                "LenovoXCC",
                "LenovoIMM",
                "Nutanix"
            ]
        },
        "api.FirmwareInfoRequest": {
            "type": "object",
            "required": [
                "bmc_type",
                "ip_address"
            ],
            "properties": {
                "bmc_type": {
                    "$ref": "#/definitions/api.BMCType"
                },
                "ip_address": {
                    "type": "string"
                }
            }
        },
        "api.FirmwareUpdateRequest": {
            "type": "object",
            "required": [
                "bmc_type",
                "firmware_path",
                "ip_address"
            ],
            "properties": {
                "bmc_type": {
                    "$ref": "#/definitions/api.BMCType"
                },
                "firmware_path": {
                    "description": "Path to the firmware file",
                    "type": "string"
                },
                "ip_address": {
                    "type": "string"
                }
            }
        },
        "api.PowerAction": {
            "type": "string",
            "enum": [
                "on",
                "off",
                "reset",
                "bmcreset"
            ],
            "x-enum-varnames": [
                "On",
                "Off",
                "Reset",
                "BMCReset"
            ]
        },
        "api.PowerRequest": {
            "type": "object",
            "required": [
                "action",
                "bmc_type",
                "ip_address"
            ],
            "properties": {
                "action": {
                    "description": "Power action (on, off, reset, bmcreset)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/api.PowerAction"
                        }
                    ]
                },
                "bmc_type": {
                    "description": "Dell, HPE, Lenovo, Nutanix, etc.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/api.BMCType"
                        }
                    ]
                },
                "ip_address": {
                    "description": "BMC IP address",
                    "type": "string"
                }
            }
        },
        "api.SystemInfoRequest": {
            "type": "object",
            "required": [
                "bmc_type",
                "ip_address"
            ],
            "properties": {
                "bmc_type": {
                    "$ref": "#/definitions/api.BMCType"
                },
                "ip_address": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
